### ISSUE TITLE
[ENHANCEMENT] Compatibility to RF 7

### ISSUE THREAD

**Issue by matthiasxv250** [d-biehl/robotframework-libraryproxy#1]
**Is your enhancement request related to a problem? Please describe.**
The current implementation does not work with robotframework version 7. Reason: The _get_result function in running.librarykeywordrunner and running.userkeywordrunner has been removed. The run function has been rewritten to take the result as a parameter. Please see the commit https://github.com/robotframework/robotframework/commit/861c65a0ad087378252e3aff376b10494081e6a2#diff-710646446c3338a3a63bffcc0b7be324b0e0df2797048057c907d7ad5d7ade6b

**Describe the solution you'd like**
Compatibility to RF 7 or even usage in 7 only.

**Comment by d-biehl** [comment]
should be fixed in the latest release
